name: Markdown link check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-link:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: umbrelladocs/action-linkspector@v1
      with:
        fail_on_error: true
        filter_mode: nofilter
